[package]
name = "udp"
version = "0.1.0"
authors = ["Christian Smith <christian@dhp.com>"]

[dependencies]
byteorder = "^1.0.0"
sha2 = "^0.5.2"
time = "^0.1.37"

[lib]
name = "udp"
path = "src/lib.rs"
